/**
 * @fileoverview gRPC-Web generated client stub for service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.1
// source: service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as service_pb from './service_pb'; // proto import: "service.proto"


export class ServesRequestsClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAddOrUpdateUserService = new grpcWeb.MethodDescriptor(
    '/service.ServesRequests/AddOrUpdateUserService',
    grpcWeb.MethodType.UNARY,
    service_pb.MessageService,
    service_pb.MessageReplyService,
    (request: service_pb.MessageService) => {
      return request.serializeBinary();
    },
    service_pb.MessageReplyService.deserializeBinary
  );

  addOrUpdateUserService(
    request: service_pb.MessageService,
    metadata?: grpcWeb.Metadata | null): Promise<service_pb.MessageReplyService>;

  addOrUpdateUserService(
    request: service_pb.MessageService,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.MessageReplyService) => void): grpcWeb.ClientReadableStream<service_pb.MessageReplyService>;

  addOrUpdateUserService(
    request: service_pb.MessageService,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.MessageReplyService) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/service.ServesRequests/AddOrUpdateUserService',
        request,
        metadata || {},
        this.methodDescriptorAddOrUpdateUserService,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/service.ServesRequests/AddOrUpdateUserService',
    request,
    metadata || {},
    this.methodDescriptorAddOrUpdateUserService);
  }

  methodDescriptorGetUserServices = new grpcWeb.MethodDescriptor(
    '/service.ServesRequests/GetUserServices',
    grpcWeb.MethodType.UNARY,
    service_pb.MessageUserId,
    service_pb.MessageReplyService,
    (request: service_pb.MessageUserId) => {
      return request.serializeBinary();
    },
    service_pb.MessageReplyService.deserializeBinary
  );

  getUserServices(
    request: service_pb.MessageUserId,
    metadata?: grpcWeb.Metadata | null): Promise<service_pb.MessageReplyService>;

  getUserServices(
    request: service_pb.MessageUserId,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.MessageReplyService) => void): grpcWeb.ClientReadableStream<service_pb.MessageReplyService>;

  getUserServices(
    request: service_pb.MessageUserId,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.MessageReplyService) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/service.ServesRequests/GetUserServices',
        request,
        metadata || {},
        this.methodDescriptorGetUserServices,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/service.ServesRequests/GetUserServices',
    request,
    metadata || {},
    this.methodDescriptorGetUserServices);
  }

}

